# Generated by Django 3.2.6 on 2025-03-14 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MRI', 'MRI'), ('EEG', 'EEG'), ('MI_RNA', 'miRNA'), ('NEUROPSYCHOLOGICAL_EVALUATION', 'Neuropsychological Evaluation')], default=None, max_length=50)),
                ('date', models.DateField()),
                ('exam_path', models.TextField()),
                ('exam_results_path', models.TextField()),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
